"""
05_motif_discovery.py
======================
Runs STREME and MEME motif discovery on AMP sequences
using precomputed length/K+R-matched background sequences.

Validation of background distributions is NOT repeated here
(already done in 04_background_sampling.py).

Usage:
    python 05_motif_discovery.py                        # both tools
    python 05_motif_discovery.py --tool cdhit           # only CD-HIT
    python 05_motif_discovery.py --tool mmseqs          # only MMseqs2
    python 05_motif_discovery.py --nmotifs 30           # custom n motifs
    python 05_motif_discovery.py --minw 4 --maxw 15     # custom width
    python 05_motif_discovery.py --overwrite            # clean output dirs
    python 05_motif_discovery.py --test                 # test mode, no results touched
"""

from __future__ import annotations

import argparse
import logging
import shutil
import subprocess
import sys
from pathlib import Path

# =====================================================
# PROJECT ROOT
# =====================================================

def _find_project_root() -> Path:
    for parent in Path(__file__).resolve().parents:
        if (parent / ".git").exists() or (parent / "pyproject.toml").exists():
            return parent
    raise RuntimeError("Could not find project root.")

PROJECT_ROOT  = _find_project_root()
CLUSTER_DIR   = PROJECT_ROOT / "results"  / "02_redundancy_reduction"
BG_DIR        = PROJECT_ROOT / "data"     / "intermediate" / "background"
MOTIF_DIR     = PROJECT_ROOT / "results"  / "04_motif_discovery"
LOGS_DIR      = PROJECT_ROOT / "logs"

# AMP FASTAs
AMP_FASTAS = {
    "cdhit":  CLUSTER_DIR / "AMP_MASTER_cdhit.fasta",
    "mmseqs": CLUSTER_DIR / "AMP_MASTER_mmseqs_rep_seq.fasta",
}

# Background FASTAs (generated by 04_background_sampling.py)
BG_FASTAS = {
    "cdhit":  BG_DIR / "background_cdhit_10x.fasta",
    "mmseqs": BG_DIR / "background_mmseqs_10x.fasta",
}

# =====================================================
# LOGGING
# =====================================================

def setup_logging() -> None:
    for d in [MOTIF_DIR, LOGS_DIR]:
        d.mkdir(parents=True, exist_ok=True)
    log_file = LOGS_DIR / "05_motif_discovery.log"
    logging.basicConfig(
        level=logging.DEBUG,
        format="%(asctime)s | %(levelname)-8s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        handlers=[
            logging.FileHandler(log_file, mode="w", encoding="utf-8"),
            logging.StreamHandler(sys.stdout),
        ],
    )

logger = logging.getLogger(__name__)

# =====================================================
# HELPERS
# =====================================================

def get_binary(name: str) -> str:
    """Find executable in PATH, exit with helpful message if missing."""
    path = shutil.which(name)
    if path is None:
        logger.error(
            "Required executable '%s' not found in PATH.\n"
            "Activate the correct conda environment or install MEME Suite.\n"
            "Check with:  which %s", name, name,
        )
        sys.exit(1)
    return path


def check_binaries() -> tuple[str, str]:
    streme_bin = get_binary("streme")
    meme_bin   = get_binary("meme")
    logger.info("STREME binary: %s", streme_bin)
    logger.info("MEME binary:   %s", meme_bin)

    for label, binary in [("STREME", streme_bin), ("MEME", meme_bin)]:
        try:
            result = subprocess.run(
                [binary, "--version"],
                capture_output=True, text=True, check=False,
            )
            version = (result.stdout or result.stderr).strip().splitlines()
            logger.info("%s version: %s", label,
                        version[0] if version else "unknown")
        except Exception:
            logger.warning("%s version: could not retrieve", label)

    return streme_bin, meme_bin


def prepare_dir(path: Path, overwrite: bool) -> None:
    """Create output dir, optionally clearing it first."""
    if path.exists() and overwrite:
        shutil.rmtree(path)
        logger.debug("Cleared existing directory: %s", path)
    path.mkdir(parents=True, exist_ok=True)


def run_cmd(cmd: list[str], label: str) -> None:
    """Log and run a command, exit on failure."""
    logger.info("Running %s:\n  %s", label, " ".join(str(c) for c in cmd))
    try:
        subprocess.run(cmd, check=True)
    except subprocess.CalledProcessError as e:
        logger.error("%s failed with return code %d", label, e.returncode)
        sys.exit(1)
    except FileNotFoundError:
        logger.error("Executable not found: %s", cmd[0])
        sys.exit(1)

# =====================================================
# STREME
# =====================================================

def run_streme(
        label:      str,
        amp_fasta:  Path,
        bg_fasta:   Path,
        streme_bin: str,
        minw:       int,
        maxw:       int,
        nmotifs:    int,
        pvt:        float,
        overwrite:  bool,
) -> Path:
    out_dir = MOTIF_DIR / f"streme_{label}"
    prepare_dir(out_dir, overwrite)

    cmd = [
        streme_bin,
        "--p",       str(amp_fasta),
        "--n",       str(bg_fasta),
        "--protein",
        "--minw",    str(minw),
        "--maxw",    str(maxw),
        "--nmotifs", str(nmotifs),
        "--pvt",     str(pvt),
        "--oc",      str(out_dir),
    ]
    run_cmd(cmd, f"STREME ({label})")
    logger.info("STREME completed: %s", out_dir)
    return out_dir

# =====================================================
# MEME
# =====================================================

def run_meme(
        label:     str,
        amp_fasta: Path,
        bg_fasta:  Path,
        meme_bin:  str,
        minw:      int,
        maxw:      int,
        nmotifs:   int,
        maxsize:   int,
        overwrite: bool,
) -> Path:
    out_dir = MOTIF_DIR / f"meme_{label}"
    prepare_dir(out_dir, overwrite)

    cmd = [
        meme_bin,
        str(amp_fasta),
        "-neg",     str(bg_fasta),
        "-mod",     "zoops",
        "-objfun",  "de",
        "-nmotifs", str(nmotifs),
        "-minw",    str(minw),
        "-maxw",    str(maxw),
        "-maxsize", str(maxsize),
        "-oc",      str(out_dir),
    ]
    run_cmd(cmd, f"MEME ({label})")
    logger.info("MEME completed: %s", out_dir)
    return out_dir

# =====================================================
# CLI
# =====================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run STREME and MEME motif discovery on AMP sequences.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python 05_motif_discovery.py                        # both tools, defaults
  python 05_motif_discovery.py --tool cdhit           # only CD-HIT
  python 05_motif_discovery.py --tool mmseqs          # only MMseqs2
  python 05_motif_discovery.py --nmotifs 30           # find 30 motifs
  python 05_motif_discovery.py --minw 4 --maxw 15     # custom width range
  python 05_motif_discovery.py --overwrite            # clear output dirs first
  python 05_motif_discovery.py --test                 # test run, separate folder
        """,
    )
    parser.add_argument("--tool",     choices=["cdhit","mmseqs","both"],
                        default="both")
    parser.add_argument("--minw",     type=int,   default=6)
    parser.add_argument("--maxw",     type=int,   default=20)
    parser.add_argument("--nmotifs",  type=int,   default=45)
    parser.add_argument("--pvt",      type=float, default=0.01,
                        help="STREME p-value threshold (default: 0.01)")
    parser.add_argument("--maxsize",  type=int,   default=10_000_000,
                        help="MEME --maxsize (default: 10000000)")
    parser.add_argument("--overwrite", action="store_true",
                        help="Clear existing output dirs before running")
    parser.add_argument("--test", action="store_true",
                        help="Test mode: outputs to results/04_motif_discovery_test/, "
                             "nmotifs=2. Does NOT touch existing results.")
    return parser.parse_args()

# =====================================================
# MAIN
# =====================================================

def main() -> None:
    setup_logging()
    args = parse_args()

    # test mode — redirect to separate folder, never touches real results
    global MOTIF_DIR
    if args.test:
        MOTIF_DIR = PROJECT_ROOT / "results" / "04_motif_discovery_test"
        args.nmotifs  = 2
        args.overwrite = True
        logger.info("TEST MODE — output dir: %s  nmotifs=2", MOTIF_DIR)
    MOTIF_DIR.mkdir(parents=True, exist_ok=True)

    logger.info("Motif discovery started.")
    logger.info(
        "Tool: %s  |  minw=%d  maxw=%d  nmotifs=%d  pvt=%.3f  overwrite=%s",
        args.tool, args.minw, args.maxw, args.nmotifs,
        args.pvt, args.overwrite,
    )

    # check input files
    to_run = ["cdhit","mmseqs"] if args.tool == "both" else [args.tool]
    for tool in to_run:
        for fasta in [AMP_FASTAS[tool], BG_FASTAS[tool]]:
            if not fasta.exists():
                logger.error("Input not found: %s", fasta)
                sys.exit(1)

    streme_bin, meme_bin = check_binaries()

    failed = []
    for tool in to_run:
        logger.info("=== %s ===", tool.upper())
        try:
            run_streme(
                label=tool, amp_fasta=AMP_FASTAS[tool],
                bg_fasta=BG_FASTAS[tool], streme_bin=streme_bin,
                minw=args.minw, maxw=args.maxw, nmotifs=args.nmotifs,
                pvt=args.pvt, overwrite=args.overwrite,
            )
            run_meme(
                label=tool, amp_fasta=AMP_FASTAS[tool],
                bg_fasta=BG_FASTAS[tool], meme_bin=meme_bin,
                minw=args.minw, maxw=args.maxw, nmotifs=args.nmotifs,
                maxsize=args.maxsize, overwrite=args.overwrite,
            )
        except SystemExit:
            failed.append(tool)

    if failed:
        logger.error("Completed WITH ERRORS: %s", failed)
        sys.exit(1)
    else:
        logger.info("Motif discovery completed successfully.")
        logger.info("Outputs in: %s", MOTIF_DIR)


if __name__ == "__main__":
    main()