"""
Usage:
    python 08_fimo_reporting.py
    python 08_fimo_reporting.py --alpha 0.01 --er_min 3
    python 08_fimo_reporting.py --test
"""

from __future__ import annotations

import argparse
import logging
import re
import sys
from itertools import combinations
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from scipy.stats import mannwhitneyu
from statsmodels.stats.multitest import multipletests

logging.getLogger("matplotlib").setLevel(logging.WARNING)
logging.getLogger("PIL").setLevel(logging.WARNING)

# =====================================================
# PROJECT ROOT
# =====================================================

def _find_project_root() -> Path:
    for parent in Path(__file__).resolve().parents:
        if (parent / ".git").exists() or (parent / "pyproject.toml").exists():
            return parent
    raise RuntimeError("Could not find project root.")

PROJECT_ROOT = _find_project_root()
ENRICH_DIR   = PROJECT_ROOT / "results" / "06_motif_statistics" / "01_fimo_enrichment"
MOTIF_DIR    = PROJECT_ROOT / "results" / "04_motif_discovery"
FIMO_BASE    = PROJECT_ROOT / "results" / "05_motif_scanning"
LOGS_DIR     = PROJECT_ROOT / "logs"

MOTIF_FILES = {
    ("cdhit",  "meme"):   MOTIF_DIR / "meme_cdhit"    / "meme.txt",
    ("mmseqs", "meme"):   MOTIF_DIR / "meme_mmseqs"   / "meme.txt",
    ("cdhit",  "streme"): MOTIF_DIR / "streme_cdhit"  / "streme.txt",
    ("mmseqs", "streme"): MOTIF_DIR / "streme_mmseqs" / "streme.txt",
}

FIMO_AMP_DIRS = {
    ("cdhit",  "meme"):   FIMO_BASE / "cdhit"  / "meme"   / "fimo_amps",
    ("mmseqs", "meme"):   FIMO_BASE / "mmseqs" / "meme"   / "fimo_amps",
    ("cdhit",  "streme"): FIMO_BASE / "cdhit"  / "streme" / "fimo_amps",
    ("mmseqs", "streme"): FIMO_BASE / "mmseqs" / "streme" / "fimo_amps",
}

PALETTE = {
    "cdhit_meme":    "#E07B54",
    "cdhit_streme":  "#C0504D",
    "mmseqs_meme":   "#4C72B0",
    "mmseqs_streme": "#2E75B6",
}
DPI = 300

# =====================================================
# LOGGING
# =====================================================

def setup_logging(out_dir: Path) -> None:
    for d in [out_dir, LOGS_DIR]:
        d.mkdir(parents=True, exist_ok=True)
    log_file = LOGS_DIR / "08_fimo_reporting.log"
    logging.basicConfig(
        level=logging.DEBUG,
        format="%(asctime)s | %(levelname)-8s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        handlers=[
            logging.FileHandler(log_file, mode="w", encoding="utf-8"),
            logging.StreamHandler(sys.stdout),
        ],
    )

logger = logging.getLogger(__name__)
sns.set_theme(style="whitegrid", font_scale=1.05)

# =====================================================
# HELPERS
# =====================================================

def clean_motif_name(x: str) -> str:
    """Remove numeric prefixes from STREME: '24-DEGEMTEEEKK' -> 'DEGEMTEEEKK'"""
    x = str(x).strip()
    x = re.sub(r"^\d+[-_]", "", x)
    return x.strip()


def load_enrichment_table() -> pd.DataFrame:
    """Load from master Excel generated by 07_fimo_enrichment.py."""
    master = ENRICH_DIR / "fimo_enrichment_master.xlsx"
    if master.exists():
        df = pd.read_excel(master, sheet_name="All_results", engine="openpyxl")
        logger.info("Loaded enrichment table: %s  (%d rows)", master.name, len(df))
        return df
    # fallback to CSV
    for csv in sorted(ENRICH_DIR.glob("*enrichment_all*.csv")):
        df = pd.read_csv(csv, sep=";", encoding="utf-8-sig")
        logger.info("Loaded fallback CSV: %s  (%d rows)", csv.name, len(df))
        return df
    raise FileNotFoundError(
        f"Could not find enrichment table in {ENRICH_DIR}. "
        "Run 07_fimo_enrichment.py first."
    )


def load_fimo_hit_counts() -> pd.DataFrame:
    """Load raw FIMO hit counts from fimo.tsv files."""
    records = []
    for (cl, tl), fimo_dir in FIMO_AMP_DIRS.items():
        tsv = fimo_dir / "fimo.tsv"
        if not tsv.exists():
            logger.warning("fimo.tsv not found: %s", tsv)
            continue
        try:
            fimo = pd.read_csv(tsv, sep="\t", comment="#", low_memory=False)
        except Exception as e:
            logger.warning("Could not read %s: %s", tsv, e)
            continue
        if fimo.empty:
            continue

        fimo.columns = [c.strip().lower().replace("-","_") for c in fimo.columns]
        mcol = next((c for c in ["motif_id","motif_alt_id"] if c in fimo.columns), None)
        scol = next((c for c in ["sequence_name","sequence"] if c in fimo.columns), None)
        if not mcol or not scol:
            continue

        fimo["_motif"] = fimo[mcol].astype(str).map(clean_motif_name)
        fimo[scol]     = fimo[scol].astype(str).str.strip()
        total_seqs     = fimo[scol].nunique()

        for motif, grp in fimo.groupby("_motif", dropna=True):
            records.append({
                "Clustering":          cl,
                "Tool":                tl,
                "Motif":               motif,
                "Total_hits":          len(grp),
                "AMP_seqs_hit":        grp[scol].nunique(),
                "AMP_total_seqs":      total_seqs,
                "AMP_hit_pct":         round(100 * grp[scol].nunique() / total_seqs, 2)
                                       if total_seqs > 0 else np.nan,
            })
    return pd.DataFrame(records) if records else pd.DataFrame()


def classify_motif(seq: str) -> str:
    seq = str(seq); L = len(seq)
    if L == 0: return "Other"
    fC  = seq.count("C") / L
    fG  = seq.count("G") / L
    fKR = (seq.count("K") + seq.count("R")) / L
    fH  = sum(seq.count(x) for x in "AILMFWVY") / L
    if fC >= 0.25:  return "Cys-rich"
    if fG >= 0.30:  return "Gly-rich"
    if fKR >= 0.35: return "Cationic"
    if fH >= 0.60:  return "Hydrophobic"
    return "Other"


def extract_consensus(motif_file: Path) -> dict[str, str]:
    """Extract consensus sequences from MEME/STREME text output."""
    if not motif_file.exists():
        return {}
    alphabet = "ACDEFGHIKLMNPQRSTVWY"
    lines    = motif_file.read_text(errors="ignore").splitlines(True)
    result   = {}
    i = 0
    while i < len(lines):
        if lines[i].startswith("MOTIF"):
            parts    = lines[i].strip().split()
            motif_id = clean_motif_name(parts[1]) if len(parts) >= 2 else ""
            i += 1
            while i < len(lines) and "letter-probability matrix" not in lines[i]:
                i += 1
            if i >= len(lines): break
            w_match = re.search(r"w=\s*(\d+)", lines[i])
            if not w_match: i += 1; continue
            width = int(w_match.group(1)); i += 1
            matrix = []
            for _ in range(width):
                if i >= len(lines): break
                row = lines[i].strip().split()
                try: matrix.append(list(map(float, row[:len(alphabet)])))
                except: pass
                i += 1
            if len(matrix) == width:
                result[motif_id] = "".join(
                    alphabet[int(np.argmax(pos))] for pos in matrix)
        else:
            i += 1
    return result


def hamming(s1: str, s2: str) -> int | None:
    if len(s1) != len(s2): return None
    return sum(c1 != c2 for c1, c2 in zip(s1, s2))

# =====================================================
# NORMALIZE
# =====================================================

def normalize(df: pd.DataFrame, hit_counts: pd.DataFrame,
              alpha: float, er_min: float) -> pd.DataFrame:
    df = df.copy()
    # rename columns for consistency
    rename = {"FDR": "FDR_corrected", "Fisher_p": "Fisher_pvalue",
               "Fisher_OR": "Fisher_oddsratio", "AMP_hits": "AMP_sequences_with_hit",
               "nonAMP_hits": "nonAMP_sequences_with_hit",
               "Total_AMP": "Total_AMP_sequences",
               "Total_nonAMP": "Total_nonAMP_sequences",
               "FDR_global": "FDR_corrected_global", "Sig_FDR": "Sig_FDR_local",
               "Sig_FDR_global": "Significant_FDR"}
    df = df.rename(columns={k: v for k, v in rename.items() if k in df.columns})

    for col in ["Clustering","Tool","Motif"]:
        df[col] = df[col].astype(str).str.strip().str.lower()
    # standardize mmseq -> mmseqs for consistency
    df["Clustering"] = df["Clustering"].str.replace(r"^mmseq$", "mmseqs", regex=True)
    df["Motif"] = df["Motif"].map(clean_motif_name)

    # FDR column to use
    if "FDR_corrected_global" in df.columns:
        df["FDR_report"] = pd.to_numeric(df["FDR_corrected_global"], errors="coerce")
    elif "FDR_corrected" in df.columns:
        df["FDR_report"] = pd.to_numeric(df["FDR_corrected"], errors="coerce")
    else:
        raise ValueError("No FDR column found.")

    for col in ["AMP_sequences_with_hit","nonAMP_sequences_with_hit",
                "Total_AMP_sequences","Total_nonAMP_sequences",
                "Enrichment_ratio","Fisher_pvalue"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    df["ER_infinite"] = (
        df.get("nonAMP_sequences_with_hit", pd.Series(dtype=float)).fillna(0).eq(0) &
        df.get("AMP_sequences_with_hit",    pd.Series(dtype=float)).fillna(0).gt(0)
    )

    finite_er = df["Enrichment_ratio"].replace([np.inf,-np.inf], np.nan)
    df["log2_ER"]   = np.log2(finite_er.clip(lower=1e-12))
    df["log10_ER"]  = np.log10(finite_er.clip(lower=1e-12))
    df["neg_log10_FDR"] = -np.log10(df["FDR_report"].clip(lower=1e-300))

    df["Motif_length"] = df["Motif"].str.len()
    df["Motif_class"]  = df["Motif"].map(classify_motif)

    df["Significant"] = (df["FDR_report"] < alpha) & (df["Enrichment_ratio"] > er_min)

    # merge hit counts
    if not hit_counts.empty:
        hc = hit_counts.copy()
        for col in ["Clustering","Tool","Motif"]:
            hc[col] = hc[col].astype(str).str.strip().str.lower()
        hc["Motif"] = hc["Motif"].map(clean_motif_name)
        # force plain str dtype to avoid Arrow/object mismatch
        for col in ["Clustering","Tool","Motif"]:
            df[col] = df[col].astype(str)
            hc[col] = hc[col].astype(str)
        df = df.merge(
            hc[["Clustering","Tool","Motif","Total_hits","AMP_hit_pct"]],
            on=["Clustering","Tool","Motif"], how="left")
    else:
        df["Total_hits"] = np.nan
        df["AMP_hit_pct"] = np.nan

    return df.dropna(subset=["Clustering","Tool","Motif","FDR_report"])

# =====================================================
# ANALYSES
# =====================================================

def analysis_summary(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    summary = (
        df.groupby(["Clustering","Tool"])
        .agg(
            n_total=("Motif","count"),
            n_sig=("Significant","sum"),
            mean_log2ER=("log2_ER", lambda x: x.replace([np.inf,-np.inf],np.nan).mean()),
            n_infinite=("ER_infinite","sum"),
            mean_length=("Motif_length","mean"),
        ).reset_index()
    )
    summary["pct_sig"] = (100 * summary["n_sig"] / summary["n_total"]).round(1)
    logger.info("\n=== Summary ===\n%s", summary.to_string(index=False))

    class_df = (
        df[df["Significant"]].groupby(["Clustering","Tool","Motif_class"])
        .size().reset_index(name="n")
    )
    return summary, class_df


def analysis_overlap(df_sig: pd.DataFrame,
                     max_mm: int = 2) -> tuple[pd.DataFrame, pd.DataFrame]:
    combo_sets = {
        (cl, tl): set(sub["Motif"].astype(str))
        for (cl, tl), sub in df_sig.groupby(["Clustering","Tool"])
    }
    exact_rows = []
    for a, b in combinations(sorted(combo_sets), 2):
        inter = combo_sets[a] & combo_sets[b]
        union = combo_sets[a] | combo_sets[b]
        exact_rows.append({
            "A": f"{a[0]}_{a[1]}", "B": f"{b[0]}_{b[1]}",
            "n_A": len(combo_sets[a]), "n_B": len(combo_sets[b]),
            "n_shared": len(inter),
            "Jaccard": round(len(inter)/len(union), 4) if union else np.nan,
            "shared_motifs": ";".join(sorted(inter)),
        })

    cons_maps = {k: extract_consensus(v) for k, v in MOTIF_FILES.items()}
    sim_rows = []
    for a, b in combinations(sorted(combo_sets), 2):
        ma = [cons_maps.get(a,{}).get(m,"") for m in combo_sets[a]]
        mb = [cons_maps.get(b,{}).get(m,"") for m in combo_sets[b]]
        ma = [x for x in ma if x]; mb = [x for x in mb if x]
        n_sim = sum(
            1 for s1 in ma if any(
                h is not None and h <= max_mm
                for h in [hamming(s1, s2) for s2 in mb])
        ) if ma and mb else np.nan
        sim_rows.append({
            "A": f"{a[0]}_{a[1]}", "B": f"{b[0]}_{b[1]}",
            "n_cons_A": len(ma), "n_cons_B": len(mb),
            "n_similar": n_sim, "max_mismatch": max_mm,
        })

    return pd.DataFrame(exact_rows), pd.DataFrame(sim_rows)


def analysis_length_meme_vs_streme(df: pd.DataFrame) -> pd.DataFrame:
    """Compare motif length between MEME and STREME, per dataset."""
    rows = []
    for cl in df["Clustering"].unique():
        meme   = df[(df["Clustering"]==cl) & (df["Tool"]=="meme")   & df["Significant"]]["Motif_length"].dropna()
        streme = df[(df["Clustering"]==cl) & (df["Tool"]=="streme") & df["Significant"]]["Motif_length"].dropna()
        if len(meme) < 2 or len(streme) < 2:
            continue
        u, p = mannwhitneyu(meme, streme, alternative="two-sided")
        d = (meme.mean() - streme.mean()) / np.sqrt(
            (meme.std()**2 + streme.std()**2) / 2)
        rows.append({
            "Clustering":         cl,
            "mean_len_meme":      round(meme.mean(),2),
            "mean_len_streme":    round(streme.mean(),2),
            "median_len_meme":    meme.median(),
            "median_len_streme":  streme.median(),
            "p_mannwhitney":      round(p, 8),
            "Cohen_d":            round(d, 4),
        })
    df_out = pd.DataFrame(rows)
    logger.info("\n=== Motif length MEME vs STREME ===\n%s", df_out.to_string(index=False))
    return df_out

# =====================================================
# FIGURES
# =====================================================

def fig_significant_bar(summary: pd.DataFrame, out_dir: Path) -> None:
    fig, ax = plt.subplots(figsize=(8, 5))
    fig.patch.set_facecolor("#fafafa"); ax.set_facecolor("#fafafa")
    labels = [f"{r.Clustering}\n{r.Tool}" for _, r in summary.iterrows()]
    colors = [PALETTE.get(f"{r.Clustering}_{r.Tool}", "#888")
              for _, r in summary.iterrows()]
    bars = ax.bar(range(len(summary)), summary["pct_sig"].values,
                  color=colors, alpha=0.85, edgecolor="white")
    for bar, n in zip(bars, summary["n_sig"].values):
        ax.text(bar.get_x()+bar.get_width()/2,
                bar.get_height()+0.5, f"n={int(n)}",
                ha="center", fontsize=10, fontweight="bold")
    ax.set_xticks(range(len(summary))); ax.set_xticklabels(labels, fontsize=10)
    ax.set_ylabel("% significant motifs"); ax.set_ylim(0, 115)
    ax.set_title("Significant enriched motifs per pipeline",fontweight="bold")
    ax.spines[["top","right"]].set_visible(False)
    fig.tight_layout()
    out = out_dir/"01_significant_motifs_bar.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight"); plt.close()
    logger.info("Fig 1: %s", out)


def fig_top_motifs(df_sig: pd.DataFrame, top_n: int, out_dir: Path) -> None:
    plot = df_sig[df_sig["log2_ER"].notna()].nlargest(top_n, "log2_ER")
    if plot.empty: return
    fig, ax = plt.subplots(figsize=(10, max(5, len(plot)*0.35)))
    fig.patch.set_facecolor("#fafafa"); ax.set_facecolor("#fafafa")
    colors = [PALETTE.get(f"{r.Clustering}_{r.Tool}", "#888")
              for _, r in plot.iterrows()]
    labels = [f"{r.Motif} ({r.Clustering}-{r.Tool})"
              for _, r in plot.iterrows()]
    ax.barh(range(len(plot)), plot["log2_ER"].values,
            color=colors, alpha=0.85, edgecolor="white")
    ax.set_yticks(range(len(plot))); ax.set_yticklabels(labels, fontsize=8)
    ax.set_xlabel("log₂ Enrichment Ratio", fontsize=10)
    ax.set_title(f"Top {top_n} motifs — log₂ ER (FDR significant)",
                 fontweight="bold")
    patches = [mpatches.Patch(color=v, label=k) for k,v in PALETTE.items()]
    ax.legend(handles=patches, fontsize=8)
    ax.spines[["top","right"]].set_visible(False)
    fig.tight_layout()
    out = out_dir/"02_top_motifs_log2ER.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight"); plt.close()
    logger.info("Fig 2: %s", out)


def fig_scatter_er_fdr(df_sig: pd.DataFrame, out_dir: Path) -> None:
    plot = df_sig.dropna(subset=["log2_ER","neg_log10_FDR"])
    if plot.empty: return
    fig, ax = plt.subplots(figsize=(8, 6))
    fig.patch.set_facecolor("#fafafa"); ax.set_facecolor("#fafafa")
    for key, sub in plot.groupby(["Clustering","Tool"]):
        color = PALETTE.get(f"{key[0]}_{key[1]}", "#888")
        ax.scatter(sub["log2_ER"], sub["neg_log10_FDR"],
                   color=color, alpha=0.75, s=40, label=f"{key[0]}-{key[1]}",
                   edgecolors="white", linewidths=0.3)
    ax.set_xlabel("log₂ Enrichment Ratio", fontsize=10)
    ax.set_ylabel("-log₁₀(FDR)", fontsize=10)
    ax.set_title("Effect size vs significance", fontweight="bold")
    ax.legend(fontsize=8)
    ax.spines[["top","right"]].set_visible(False)
    fig.tight_layout()
    out = out_dir/"03_scatter_ER_vs_FDR.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight"); plt.close()
    logger.info("Fig 3: %s", out)


def fig_class_stacked(class_df: pd.DataFrame, out_dir: Path) -> None:
    if class_df.empty: return
    pivot = class_df.pivot_table(
        index=["Clustering","Tool"], columns="Motif_class",
        values="n", fill_value=0)
    fig, ax = plt.subplots(figsize=(9, 5))
    fig.patch.set_facecolor("#fafafa"); ax.set_facecolor("#fafafa")
    pivot.plot(kind="bar", stacked=True, ax=ax,
               colormap="tab10", edgecolor="white", alpha=0.85)
    ax.set_xlabel(""); ax.set_ylabel("Number of significant motifs")
    ax.set_title("Motif class composition — significant motifs",
                 fontweight="bold")
    ax.tick_params(axis="x", rotation=30)
    ax.legend(title="Class", bbox_to_anchor=(1,1), fontsize=8)
    ax.spines[["top","right"]].set_visible(False)
    fig.tight_layout()
    out = out_dir/"04_motif_class_stacked.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight"); plt.close()
    logger.info("Fig 4: %s", out)


def fig_top_hit_frequency(df_sig: pd.DataFrame, top_n: int,
                           out_dir: Path) -> None:
    if "AMP_hit_pct" not in df_sig.columns: return
    plot = df_sig.dropna(subset=["AMP_hit_pct"]).nlargest(top_n, "AMP_hit_pct")
    if plot.empty: return
    fig, ax = plt.subplots(figsize=(10, max(5, len(plot)*0.35)))
    fig.patch.set_facecolor("#fafafa"); ax.set_facecolor("#fafafa")
    colors = [PALETTE.get(f"{r.Clustering}_{r.Tool}", "#888")
              for _, r in plot.iterrows()]
    labels = [f"{r.Motif} ({r.Clustering}-{r.Tool})"
              for _, r in plot.iterrows()]
    ax.barh(range(len(plot)), plot["AMP_hit_pct"].values,
            color=colors, alpha=0.85, edgecolor="white")
    ax.set_yticks(range(len(plot))); ax.set_yticklabels(labels, fontsize=8)
    ax.set_xlabel("% AMP sequences with ≥1 hit", fontsize=10)
    ax.set_title(f"Top {top_n} motifs — AMP hit frequency",
                 fontweight="bold")
    ax.spines[["top","right"]].set_visible(False)
    fig.tight_layout()
    out = out_dir/"05_top_amp_hit_frequency.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight"); plt.close()
    logger.info("Fig 5: %s", out)


def fig_length_meme_vs_streme(df: pd.DataFrame, length_stats: pd.DataFrame,
                               out_dir: Path) -> None:
    """KDE + boxplot comparing motif lengths MEME vs STREME."""
    sig = df[df["Significant"]].copy()
    if sig.empty: return

    clusterings = sig["Clustering"].unique()
    fig, axes = plt.subplots(len(clusterings), 2,
                              figsize=(12, 4*len(clusterings)))
    if len(clusterings) == 1:
        axes = [axes]
    fig.patch.set_facecolor("#fafafa")

    for i, cl in enumerate(sorted(clusterings)):
        meme   = sig[(sig["Clustering"]==cl) & (sig["Tool"]=="meme")]["Motif_length"].dropna()
        streme = sig[(sig["Clustering"]==cl) & (sig["Tool"]=="streme")]["Motif_length"].dropna()

        # KDE panel
        ax_kde = axes[i][0]; ax_kde.set_facecolor("#fafafa")
        if len(meme) > 1:
            sns.kdeplot(meme, fill=True, alpha=0.5,
                        color=PALETTE.get(f"{cl}_meme", "#E07B54"),
                        label=f"MEME (n={len(meme)}, mean={meme.mean():.1f})",
                        ax=ax_kde)
        if len(streme) > 1:
            sns.kdeplot(streme, fill=True, alpha=0.5,
                        color=PALETTE.get(f"{cl}_streme", "#C0504D"),
                        label=f"STREME (n={len(streme)}, mean={streme.mean():.1f})",
                        ax=ax_kde)

        # annotate p-value if available
        row = length_stats[length_stats["Clustering"]==cl]
        if not row.empty:
            p = row["p_mannwhitney"].values[0]
            d = row["Cohen_d"].values[0]
            ax_kde.annotate(
                f"Mann-Whitney p={p:.3e}\nCohen d={d:.3f}",
                xy=(0.05, 0.90), xycoords="axes fraction",
                fontsize=8,
                bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="#ddd"))

        ax_kde.set_xlabel("Motif length (aa)", fontsize=9)
        ax_kde.set_ylabel("Density", fontsize=9)
        ax_kde.set_title(f"{cl.upper()} — Length KDE: MEME vs STREME",
                          fontweight="bold", fontsize=10)
        ax_kde.legend(fontsize=8)
        ax_kde.spines[["top","right"]].set_visible(False)

        # boxplot panel
        ax_box = axes[i][1]; ax_box.set_facecolor("#fafafa")
        data   = [meme.values, streme.values]
        colors_box = [PALETTE.get(f"{cl}_meme", "#E07B54"),
                      PALETTE.get(f"{cl}_streme", "#C0504D")]
        bp = ax_box.boxplot(data, tick_labels=["MEME","STREME"],
                             patch_artist=True, showfliers=True,
                             medianprops={"color":"black","lw":1.5})
        for patch, c in zip(bp["boxes"], colors_box):
            patch.set_facecolor(c); patch.set_alpha(0.75)
        ax_box.set_ylabel("Motif length (aa)", fontsize=9)
        ax_box.set_title(f"{cl.upper()} — Boxplot",
                          fontweight="bold", fontsize=10)
        ax_box.spines[["top","right"]].set_visible(False)

    fig.suptitle("Motif length: MEME vs STREME (significant motifs)",
                 fontsize=13, fontweight="bold")
    fig.tight_layout()
    out = out_dir/"06_motif_length_meme_vs_streme.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight"); plt.close()
    logger.info("Fig 6: %s", out)

# =====================================================
# CLI
# =====================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="FIMO reporting and motif interpretation.")
    parser.add_argument("--alpha",    type=float, default=0.05)
    parser.add_argument("--er_min",   type=float, default=2.0)
    parser.add_argument("--top_n",    type=int,   default=25)
    parser.add_argument("--max_mm",   type=int,   default=2,
                        help="Max mismatches for consensus similarity (default 2)")
    parser.add_argument("--test", action="store_true",
                        help="Output to results/06_motif_statistics_test/02_fimo_reporting/")
    return parser.parse_args()

# =====================================================
# MAIN
# =====================================================

def main() -> None:
    args = parse_args()
    out_dir = PROJECT_ROOT / (
        "results/06_motif_statistics_test/02_fimo_reporting"
        if args.test else
        "results/06_motif_statistics/02_fimo_reporting"
    )
    setup_logging(out_dir)
    logger.info("FIMO reporting started.  alpha=%.3f  er_min=%.1f  top_n=%d",
                args.alpha, args.er_min, args.top_n)

    # load
    df_raw   = load_enrichment_table()
    hc       = load_fimo_hit_counts()
    logger.info("Hit counts loaded: %d entries", len(hc))

    # normalize
    df = normalize(df_raw, hc, args.alpha, args.er_min)
    df_sig = df[df["Significant"]].copy()
    logger.info("Total motifs: %d  |  Significant: %d", len(df), len(df_sig))

    # analyses
    summary, class_df    = analysis_summary(df)
    exact_ov, sim_ov     = analysis_overlap(df_sig, args.max_mm)
    length_stats         = analysis_length_meme_vs_streme(df)

    # save tables
    master_out = out_dir / "fimo_reporting_master.xlsx"
    with pd.ExcelWriter(master_out, engine="openpyxl") as w:
        df.to_excel(w,        sheet_name="All_normalized",  index=False)
        df_sig.to_excel(w,    sheet_name="Significant",     index=False)
        summary.to_excel(w,   sheet_name="Summary",         index=False)
        class_df.to_excel(w,  sheet_name="Motif_classes",   index=False)
        exact_ov.to_excel(w,  sheet_name="Overlap_exact",   index=False)
        sim_ov.to_excel(w,    sheet_name="Overlap_similar", index=False)
        length_stats.to_excel(w, sheet_name="Length_stats", index=False)
        # GraphPad sheets — flatten MultiIndex columns before writing
        gp_hit = df_sig.pivot_table(index="Motif", columns=["Clustering","Tool"],
                           values="AMP_hit_pct", aggfunc="mean")
        gp_hit.columns = ["_".join(map(str,c)) for c in gp_hit.columns]
        gp_hit.reset_index().to_excel(w, sheet_name="GP_AMP_hit_pct", index=False)

        gp_er = df_sig.pivot_table(index="Motif", columns=["Clustering","Tool"],
                           values="log2_ER", aggfunc="mean")
        gp_er.columns = ["_".join(map(str,c)) for c in gp_er.columns]
        gp_er.reset_index().to_excel(w, sheet_name="GP_log2ER", index=False)
        for cl in df["Clustering"].unique():
            for tl in ["meme","streme"]:
                sub = df[(df["Clustering"]==cl) & (df["Tool"]==tl) &
                         df["Significant"]]["Motif_length"]
                if not sub.empty:
                    pd.DataFrame({"Motif_length": sub.values}).to_excel(
                        w, sheet_name=f"GP_len_{cl[:4]}_{tl[:4]}", index=False)
    logger.info("Master Excel saved: %s", master_out)

    # figures
    fig_significant_bar(summary, out_dir)
    fig_top_motifs(df_sig, args.top_n, out_dir)
    fig_scatter_er_fdr(df_sig, out_dir)
    fig_class_stacked(class_df, out_dir)
    fig_top_hit_frequency(df_sig, args.top_n, out_dir)
    fig_length_meme_vs_streme(df, length_stats, out_dir)

    logger.info("FIMO reporting completed successfully.")
    logger.info("Outputs: %s", out_dir)

if __name__ == "__main__":
    main()