"""
10_motif_family_reporting.py
=============================
Final reporting of robust motif families identified by TOMTOM clustering.
Loads from motif_families_master.xlsx generated by 09_motif_families_tomtom.py.

Figures:
  01_class_distribution.png        — bar chart of motif classes
  02_top_families_er.png           — top families by enrichment ratio
  03_n_pipelines_bar.png           — robustness distribution
  04_pipeline_heatmap.png          — family × pipeline presence matrix
  05_er_vs_amp_hits.png            — enrichment vs AMP coverage scatter
  06_bubble_er_fdr.png             — enrichment landscape bubble chart

Usage:
    python 10_motif_family_reporting.py
    python 10_motif_family_reporting.py --top_n 20
    python 10_motif_family_reporting.py --test
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns

logging.getLogger("matplotlib").setLevel(logging.WARNING)
logging.getLogger("PIL").setLevel(logging.WARNING)

# =====================================================
# PROJECT ROOT
# =====================================================

def _find_project_root() -> Path:
    for parent in Path(__file__).resolve().parents:
        if (parent / ".git").exists() or (parent / "pyproject.toml").exists():
            return parent
    raise RuntimeError("Could not find project root.")

PROJECT_ROOT = _find_project_root()
FAMILIES_DIR = PROJECT_ROOT / "results" / "07_motif_families" / "01_tomtom"
LOGS_DIR     = PROJECT_ROOT / "logs"

PALETTE = {
    "Cys-rich":     "#E07B54",
    "Cationic":     "#4C72B0",
    "Hydrophobic":  "#3BAF77",
    "Amphipathic":  "#2E86AB",
    "Gly-rich":     "#F0C040",
    "Anionic":      "#C0504D",
    "Pro-rich":     "#9B59B6",
    "Aromatic":     "#1ABC9C",
    "His-rich":     "#E67E22",
    "Other":        "#AAAAAA",
}
DPI = 300

# =====================================================
# LOGGING
# =====================================================

def setup_logging(out_dir: Path) -> None:
    for d in [out_dir, LOGS_DIR]:
        d.mkdir(parents=True, exist_ok=True)
    log_file = LOGS_DIR / "10_motif_family_reporting.log"
    logging.basicConfig(
        level=logging.DEBUG,
        format="%(asctime)s | %(levelname)-8s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        handlers=[
            logging.FileHandler(log_file, mode="w", encoding="utf-8"),
            logging.StreamHandler(sys.stdout),
        ],
    )

logger = logging.getLogger(__name__)
sns.set_theme(style="whitegrid", font_scale=1.05)

# =====================================================
# HELPERS
# =====================================================

def finite(s: pd.Series) -> pd.Series:
    return pd.to_numeric(s, errors="coerce").replace([np.inf, -np.inf], np.nan)


def legend_patches() -> list:
    return [mpatches.Patch(color=v, label=k, alpha=0.85)
            for k, v in PALETTE.items()]


def class_color(cls: str) -> str:
    return PALETTE.get(str(cls).strip(), "#AAAAAA")


def load_sheet(path: Path, sheet: str) -> pd.DataFrame:
    try:
        df = pd.read_excel(path, sheet_name=sheet, engine="openpyxl")
        logger.info("Loaded sheet '%s': %d rows", sheet, len(df))
        return df
    except Exception as e:
        logger.warning("Could not load sheet '%s': %s", sheet, e)
        return pd.DataFrame()

# =====================================================
# FIGURES
# =====================================================

def fig_class_distribution(df: pd.DataFrame, out_dir: Path) -> None:
    col = "Rep_class" if "Rep_class" in df.columns else "Representative_class"
    if col not in df.columns: return

    counts = (df.groupby(col, dropna=False).size()
               .reset_index(name="n")
               .sort_values("n", ascending=False))
    if counts.empty: return

    fig, ax = plt.subplots(figsize=(8, 5))
    fig.patch.set_facecolor("#fafafa"); ax.set_facecolor("#fafafa")
    colors = [class_color(c) for c in counts[col]]
    bars = ax.bar(range(len(counts)), counts["n"].values,
                  color=colors, alpha=0.85, edgecolor="white")
    for bar, n in zip(bars, counts["n"].values):
        ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.05,
                str(int(n)), ha="center", fontsize=9, fontweight="bold")
    ax.set_xticks(range(len(counts)))
    ax.set_xticklabels(counts[col].tolist(), rotation=25, ha="right", fontsize=10)
    ax.set_ylabel("Number of robust motif families", fontsize=10)
    ax.set_title("Robust motif family classes", fontweight="bold")
    ax.legend(handles=legend_patches(), fontsize=8, bbox_to_anchor=(1,1))
    ax.spines[["top","right"]].set_visible(False)
    fig.tight_layout()
    out = out_dir / "01_class_distribution.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight"); plt.close()
    logger.info("Fig 1: %s", out)


def fig_top_families_er(df: pd.DataFrame, top_n: int, out_dir: Path) -> None:
    er_col  = "median_ER"
    rep_col = "Rep_motif" if "Rep_motif" in df.columns else "Representative_motif"
    cls_col = "Rep_class" if "Rep_class" in df.columns else "Representative_class"
    np_col  = "n_pipelines"

    needed = [er_col, rep_col, cls_col, np_col]
    if any(c not in df.columns for c in needed): return

    top = (df.dropna(subset=[er_col])
             .sort_values([np_col, er_col, "n_motifs"],
                          ascending=[False, False, False])
             .head(top_n)
             .sort_values(er_col, ascending=True)
             .copy())
    if top.empty: return

    fig, ax = plt.subplots(figsize=(10, max(5, len(top)*0.42)))
    fig.patch.set_facecolor("#fafafa"); ax.set_facecolor("#fafafa")
    colors = [class_color(c) for c in top[cls_col]]
    bars = ax.barh(range(len(top)), top[er_col].values,
                   color=colors, alpha=0.85, edgecolor="white")
    # annotate n_pipelines
    for i, (bar, np_) in enumerate(zip(bars, top[np_col].values)):
        ax.text(bar.get_width()+0.5, bar.get_y()+bar.get_height()/2,
                f"{int(np_)}p", va="center", fontsize=7, color="#555")
    ax.set_yticks(range(len(top)))
    ax.set_yticklabels(top[rep_col].astype(str).tolist(), fontsize=8)
    ax.set_xlabel("Median Enrichment Ratio", fontsize=10)
    ax.set_title(f"Top {top_n} robust motif families\n(annotation = n pipelines)",
                 fontweight="bold")
    ax.legend(handles=legend_patches(), fontsize=8, loc="lower right")
    ax.spines[["top","right"]].set_visible(False)
    fig.tight_layout()
    out = out_dir / "02_top_families_er.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight"); plt.close()
    logger.info("Fig 2: %s", out)


def fig_n_pipelines_bar(df: pd.DataFrame, out_dir: Path) -> None:
    if "n_pipelines" not in df.columns: return
    counts = df["n_pipelines"].value_counts().sort_index()
    if counts.empty: return

    fig, ax = plt.subplots(figsize=(6, 4))
    fig.patch.set_facecolor("#fafafa"); ax.set_facecolor("#fafafa")
    bars = ax.bar(counts.index.astype(str), counts.values,
                  color="#4C72B0", alpha=0.85, edgecolor="white")
    for bar, n in zip(bars, counts.values):
        ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.05,
                str(int(n)), ha="center", fontsize=9, fontweight="bold")
    ax.set_xlabel("Number of pipelines sharing family", fontsize=10)
    ax.set_ylabel("Number of families", fontsize=10)
    ax.set_title("Family robustness distribution", fontweight="bold")
    ax.spines[["top","right"]].set_visible(False)
    fig.tight_layout()
    out = out_dir / "03_n_pipelines_bar.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight"); plt.close()
    logger.info("Fig 3: %s", out)


def fig_pipeline_heatmap(presence: pd.DataFrame, out_dir: Path) -> None:
    if presence.empty or "Family_ID" not in presence.columns: return
    pres = presence.set_index("Family_ID")
    pipeline_cols = [c for c in pres.columns if c != "Family_ID"]
    if not pipeline_cols: return
    pres = pres[pipeline_cols].astype(float)

    fig, ax = plt.subplots(figsize=(max(6, len(pipeline_cols)*1.8),
                                    max(4, len(pres)*0.28)))
    fig.patch.set_facecolor("#fafafa")
    sns.heatmap(pres, cmap="YlOrRd", linewidths=0.3, linecolor="#eeeeee",
                vmin=0, vmax=1, ax=ax,
                cbar_kws={"label":"Present","shrink":0.6})
    ax.set_title("Motif family presence across pipelines", fontweight="bold")
    ax.set_xlabel(""); ax.set_ylabel("")
    plt.xticks(rotation=30, ha="right", fontsize=9)
    plt.yticks(fontsize=7)
    fig.tight_layout()
    out = out_dir / "04_pipeline_heatmap.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight"); plt.close()
    logger.info("Fig 4: %s", out)


def fig_er_vs_amp_hits(df: pd.DataFrame, out_dir: Path) -> None:
    er_col  = "median_ER"
    hit_col = "max_AMP_hits"
    rep_col = "Rep_motif" if "Rep_motif" in df.columns else "Representative_motif"
    cls_col = "Rep_class" if "Rep_class" in df.columns else "Representative_class"

    if any(c not in df.columns for c in [er_col, hit_col]): return
    plot = df.dropna(subset=[er_col, hit_col]).copy()
    if plot.empty: return

    fig, ax = plt.subplots(figsize=(9, 6))
    fig.patch.set_facecolor("#fafafa"); ax.set_facecolor("#fafafa")
    colors = [class_color(c) for c in plot[cls_col]]
    sizes  = (plot["n_motifs"].fillna(1) * 40).clip(lower=30, upper=400)
    ax.scatter(plot[er_col], plot[hit_col],
               c=colors, s=sizes, alpha=0.75,
               edgecolors="white", linewidths=0.4)
    for _, r in plot.nlargest(8, er_col).iterrows():
        ax.annotate(str(r[rep_col]), (r[er_col], r[hit_col]),
                    fontsize=7, xytext=(3,3), textcoords="offset points")
    ax.set_xlabel("Median Enrichment Ratio", fontsize=10)
    ax.set_ylabel("Max AMP sequences with hit", fontsize=10)
    ax.set_title("Enrichment vs AMP coverage per family\n(size = n motifs in family)",
                 fontweight="bold")
    ax.legend(handles=legend_patches(), fontsize=8)
    ax.spines[["top","right"]].set_visible(False)
    fig.tight_layout()
    out = out_dir / "05_er_vs_amp_hits.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight"); plt.close()
    logger.info("Fig 5: %s", out)


def fig_bubble_er_fdr(df: pd.DataFrame, out_dir: Path) -> None:
    er_col  = "median_ER"
    fdr_col = "min_FDR"
    rep_col = "Rep_motif" if "Rep_motif" in df.columns else "Representative_motif"
    cls_col = "Rep_class" if "Rep_class" in df.columns else "Representative_class"

    if any(c not in df.columns for c in [er_col, fdr_col]): return
    plot = df.copy()
    plot[er_col]  = finite(plot[er_col])
    plot[fdr_col] = pd.to_numeric(plot[fdr_col], errors="coerce")
    plot = plot.dropna(subset=[er_col, fdr_col])
    if plot.empty: return

    plot["log2_ER"]      = np.log2(plot[er_col].clip(lower=1e-12))
    plot["neg_log10_FDR"]= -np.log10(plot[fdr_col].clip(lower=1e-300))

    size_col = "n_motifs" if "n_motifs" in plot.columns else "n_unique_motifs"
    sizes = (plot.get(size_col, pd.Series([1]*len(plot))).fillna(1) * 40
             ).clip(lower=30, upper=400)
    colors = [class_color(c) for c in plot[cls_col]]

    fig, ax = plt.subplots(figsize=(10, 7))
    fig.patch.set_facecolor("#fafafa"); ax.set_facecolor("#fafafa")
    ax.scatter(plot["log2_ER"], plot["neg_log10_FDR"],
               s=sizes, c=colors, alpha=0.7,
               edgecolors="white", linewidths=0.4)
    for _, r in plot.nlargest(8, "neg_log10_FDR").iterrows():
        ax.annotate(str(r[rep_col]),
                    (r["log2_ER"], r["neg_log10_FDR"]),
                    fontsize=7, xytext=(3,3),
                    textcoords="offset points")
    ax.set_xlabel("log₂ Median Enrichment Ratio", fontsize=10)
    ax.set_ylabel("-log₁₀(min FDR)", fontsize=10)
    ax.set_title("Motif family enrichment landscape\n(size = n motifs in family)",
                 fontweight="bold")
    ax.legend(handles=legend_patches(), fontsize=8)
    ax.spines[["top","right"]].set_visible(False)
    fig.tight_layout()
    out = out_dir / "06_bubble_er_fdr.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight"); plt.close()
    logger.info("Fig 6: %s", out)

def fig_class_overview(robust: pd.DataFrame, summary: pd.DataFrame,
                        all_motifs: pd.DataFrame, out_dir: Path) -> None:
    """
    3-panel figure:
    A — class distribution of ALL significant motifs
    B — class distribution of ALL family representatives (171 families)
    C — boxplot of median ER by class (all families)
    """
    cls_col = "Rep_class" if "Rep_class" in summary.columns \
              else "Representative_class"
    mot_cls = "Motif_class" if "Motif_class" in all_motifs.columns else None

    fig, axes = plt.subplots(1, 3, figsize=(16, 5))
    fig.patch.set_facecolor("#fafafa")

    # ---- Panel A: all significant motifs ----
    ax = axes[0]; ax.set_facecolor("#fafafa")
    if mot_cls and not all_motifs.empty:
        counts_a = (all_motifs.groupby(mot_cls, dropna=False).size()
                    .reset_index(name="n").sort_values("n", ascending=False))
        colors_a = [class_color(c) for c in counts_a[mot_cls]]
        bars = ax.bar(range(len(counts_a)), counts_a["n"].values,
                      color=colors_a, alpha=0.85, edgecolor="white")
        for bar, n in zip(bars, counts_a["n"].values):
            ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.3,
                    str(int(n)), ha="center", fontsize=8, fontweight="bold")
        ax.set_xticks(range(len(counts_a)))
        ax.set_xticklabels(counts_a[mot_cls].tolist(),
                           rotation=25, ha="right", fontsize=9)
        ax.set_title(f"A. All significant motifs\n(n={len(all_motifs)})",
                     fontweight="bold", fontsize=10)
    else:
        ax.set_title("A. All significant motifs\n(data not available)",
                     fontweight="bold", fontsize=10)
    ax.set_ylabel("Count", fontsize=9)
    ax.spines[["top","right"]].set_visible(False)

    # ---- Panel B: all family representatives ----
    ax = axes[1]; ax.set_facecolor("#fafafa")
    if cls_col in summary.columns and not summary.empty:
        counts_b = (summary.groupby(cls_col, dropna=False).size()
                    .reset_index(name="n").sort_values("n", ascending=False))
        colors_b = [class_color(c) for c in counts_b[cls_col]]
        bars = ax.bar(range(len(counts_b)), counts_b["n"].values,
                      color=colors_b, alpha=0.85, edgecolor="white")
        for bar, n in zip(bars, counts_b["n"].values):
            ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.3,
                    str(int(n)), ha="center", fontsize=8, fontweight="bold")
        ax.set_xticks(range(len(counts_b)))
        ax.set_xticklabels(counts_b[cls_col].tolist(),
                           rotation=25, ha="right", fontsize=9)
        ax.set_title(f"B. All family representatives\n(n={len(summary)} families)",
                     fontweight="bold", fontsize=10)
    ax.set_ylabel("Count", fontsize=9)
    ax.spines[["top","right"]].set_visible(False)

    # ---- Panel C: ER boxplot by class ----
    ax = axes[2]; ax.set_facecolor("#fafafa")
    if cls_col in summary.columns and "median_ER" in summary.columns:
        plot_c = summary.copy()
        plot_c["median_ER"] = finite(plot_c["median_ER"])
        plot_c = plot_c.dropna(subset=["median_ER", cls_col])
        classes = (plot_c.groupby(cls_col)["median_ER"]
                   .median().sort_values(ascending=False).index.tolist())
        data    = [plot_c[plot_c[cls_col]==cl]["median_ER"].values
                   for cl in classes]
        colors_c= [class_color(cl) for cl in classes]
        bp = ax.boxplot(data, tick_labels=classes, patch_artist=True,
                        showfliers=True,
                        medianprops={"color":"black","lw":1.5})
        for patch, c in zip(bp["boxes"], colors_c):
            patch.set_facecolor(c); patch.set_alpha(0.75)
        ax.set_title("C. Enrichment Ratio by class\n(all families)",
                     fontweight="bold", fontsize=10)
        ax.set_ylabel("Median Enrichment Ratio", fontsize=9)
        plt.setp(ax.get_xticklabels(), rotation=25, ha="right", fontsize=9)
    ax.spines[["top","right"]].set_visible(False)

    fig.suptitle("Motif class overview — all levels of analysis",
                 fontsize=13, fontweight="bold")
    fig.tight_layout()
    out = out_dir / "07_class_overview_all.png"
    fig.savefig(out, dpi=DPI, bbox_inches="tight"); plt.close()
    logger.info("Fig 7: %s", out)

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Final reporting of robust AMP motif families.")
    parser.add_argument("--top_n", type=int, default=15)
    parser.add_argument("--test",  action="store_true",
                        help="Output to results/07_motif_families_test/02_reporting/")
    return parser.parse_args()

# =====================================================
# MAIN
# =====================================================

def main() -> None:
    args = parse_args()
    out_dir = PROJECT_ROOT / (
        "results/07_motif_families_test/02_reporting"
        if args.test else
        "results/07_motif_families/02_reporting"
    )
    setup_logging(out_dir)
    logger.info("Motif family reporting started. top_n=%d", args.top_n)

    # load from master Excel
    master_xlsx = FAMILIES_DIR / "motif_families_master.xlsx"
    if not master_xlsx.exists():
        logger.error("Input not found: %s — run 09_motif_families_tomtom.py first.",
                     master_xlsx)
        sys.exit(1)

    robust   = load_sheet(master_xlsx, "Robust_families")
    summary  = load_sheet(master_xlsx, "Family_summary")
    presence = load_sheet(master_xlsx, "Pipeline_presence")
    all_motifs = load_sheet(master_xlsx, "All_motifs_with_family")

    if robust.empty:
        logger.error("No robust families found. Check script 09 output.")
        sys.exit(1)

    # numeric normalization
    for df in [robust, summary]:
        for col in ["median_ER","min_FDR","n_motifs","n_pipelines",
                    "max_AMP_hits","n_motifs"]:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="coerce")
        if "median_ER" in df.columns:
            df["median_ER"] = finite(df["median_ER"])

    # sort robust families
    robust = robust.sort_values(
        ["n_pipelines","median_ER","n_motifs"],
        ascending=[False, False, False]
    ).copy()

    # summary stats
    stats = pd.DataFrame([{
        "n_robust_families":  len(robust),
        "n_total_families":   len(summary),
        "n_singletons":       (summary["n_motifs"] == 1).sum()
                              if "n_motifs" in summary.columns else np.nan,
        "mean_n_pipelines":   robust["n_pipelines"].mean(),
        "median_ER_all":      finite(robust["median_ER"]).median(),
        "mean_ER_all":        finite(robust["median_ER"]).mean(),
    }])
    logger.info("\n=== Summary stats ===\n%s", stats.to_string(index=False))

    # class distribution
    cls_col = "Rep_class" if "Rep_class" in robust.columns else "Representative_class"
    class_dist = (
        robust.groupby(cls_col, dropna=False).size()
        .reset_index(name="n").sort_values("n", ascending=False)
    )
    logger.info("\n=== Class distribution ===\n%s",
                class_dist.to_string(index=False))

    # top shortlist
    top = robust.head(args.top_n).copy()

    # save master Excel
    out_xlsx = out_dir / "motif_family_reporting.xlsx"
    with pd.ExcelWriter(out_xlsx, engine="openpyxl") as w:
        robust.to_excel(w,      sheet_name="Robust_families",    index=False)
        top.to_excel(w,         sheet_name=f"Top{args.top_n}",   index=False)
        class_dist.to_excel(w,  sheet_name="Class_distribution", index=False)
        stats.to_excel(w,       sheet_name="Summary_stats",      index=False)
        summary.to_excel(w,     sheet_name="All_families",       index=False)
        # GraphPad
        gp = robust[["Family_ID","Rep_motif","median_ER",
                      "n_pipelines","n_motifs"]].copy() \
             if "Rep_motif" in robust.columns else robust
        gp.to_excel(w, sheet_name="GP_robust", index=False)
        class_dist.to_excel(w, sheet_name="GP_class_dist", index=False)

        # GP Fig 7 — class counts at all 3 levels
        cls_col = "Rep_class" if "Rep_class" in summary.columns \
                  else "Representative_class"
        mot_cls = "Motif_class" if "Motif_class" in all_motifs.columns else None

        # Panel A: all motifs
        if mot_cls and not all_motifs.empty:
            gp_a = (all_motifs.groupby(mot_cls, dropna=False).size()
                    .reset_index(name="n_all_motifs"))
            gp_a.to_excel(w, sheet_name="GP_Fig7A_all_motifs", index=False)

        # Panel B: all family reps
        if cls_col in summary.columns:
            gp_b = (summary.groupby(cls_col, dropna=False).size()
                    .reset_index(name="n_families"))
            gp_b.to_excel(w, sheet_name="GP_Fig7B_family_reps", index=False)

        # Panel C: ER by class — wide format (one column per class)
        if cls_col in summary.columns and "median_ER" in summary.columns:
            er_by_class = {}
            for cl, grp in summary.groupby(cls_col):
                er_by_class[str(cl)] = grp["median_ER"].dropna().values
            max_len = max(len(v) for v in er_by_class.values()) if er_by_class else 0
            gp_c = pd.DataFrame({
                k: pd.Series(v) for k, v in er_by_class.items()
            })
            gp_c.to_excel(w, sheet_name="GP_Fig7C_ER_by_class", index=False)
    logger.info("Master Excel: %s", out_xlsx)

    # figures
    fig_class_distribution(robust, out_dir)
    fig_top_families_er(robust, args.top_n, out_dir)
    fig_n_pipelines_bar(robust, out_dir)
    fig_pipeline_heatmap(presence, out_dir)
    fig_er_vs_amp_hits(robust, out_dir)
    fig_bubble_er_fdr(robust, out_dir)
    fig_class_overview(robust, summary, all_motifs, out_dir)

    # log top families
    rep_col = "Rep_motif" if "Rep_motif" in robust.columns else "Representative_motif"
    preview = ["Family_ID", rep_col, cls_col, "n_motifs",
               "n_pipelines", "median_ER", "min_FDR"]
    preview = [c for c in preview if c in robust.columns]
    logger.info("\nTop 10 robust families:\n%s",
                robust[preview].head(10).to_string(index=False))

    logger.info("Motif family reporting completed successfully.")
    logger.info("Outputs: %s", out_dir)


if __name__ == "__main__":
    main()